apiVersion: v1
kind: PersistentVolume
metadata:
        name: apache-persistent-storage1
        namespace: kube-system
        labels:
                app: tomcat
                tier: frontend
spec:
        capacity:
                storage: 2Gi
        accessModes:
                - ReadWriteMany
        hostPath:
                path: "/var/www/html"
---

apiVersion: v1
kind: PersistentVolume
metadata:
        name: mysql-persistent-storage1
        namespace: kube-system
        labels:
                app: tomcat
                tier: mysql
spec:
        capacity:
                storage: 2Gi
        accessModes:
                - ReadWriteMany
        hostPath:
                path: "/var/lib/mysql"


---

apiVersion: v1
kind: PersistentVolume
metadata:
        name: tomcat-persistent-storage1
        namespace: kube-system
        labels:
                app: tomcat
                tier: webapp
spec:
        capacity:
                storage: 2Gi
        accessModes:
                - ReadWriteMany
        hostPath:
                path: "/usr/local/tomcat/webapps"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: apache-persistent-storage1
        namespace: kube-system
        labels:
                app: tomcat
                tier: frontend
spec:
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 1Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: mysql-persistent-storage1
        namespace: kube-system
        labels:
                app: tomcat
                tier: mysql
spec:
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 1Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: tomcat-persistent-storage1
        namespace: kube-system
        labels:
                app: tomcat
                tier: webapp

spec:
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
        name: tomcat-mysql
        namespace: kube-system
        labels:
                app: tomcat
spec:
        type: NodePort

        ports:

                - nodePort: 32023
                  name: "22"
                  port: 22
                  targetPort: 22

                - nodePort: 32024
                  name: "8080"
                  port: 8080
                  targetPort: 8080

                - nodePort: 32025
                  name: "80"
                  port: 80
                  targetPort: 80

        selector:
                app: tomcat
                tier: mysql



---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: tomcat-mysql
        namespace: kube-system
        labels:
                app: tomcat
spec:
        selector:
                matchLabels:
                        app: tomcat
                        tier: mysql

        strategy:
                type: Recreate
        template:
                metadata:
                        labels:
                                app: tomcat
                                tier: mysql

                spec:
                        containers:


                                - image: 192.168.0.6:5000/apache_newarch:2
                                  name: apache
                                  ports:
                                          - containerPort: 80

                                  volumeMounts:
                                          - name: apache-persistent-storage1
                                            mountPath: /var/www/html



                                - image: 192.168.0.6:5000/ssharch:2
                                  name: sshd
                                  ports:
                                          - containerPort: 22
                                            name: sshd
                                  volumeMounts:

                                          - name: tomcatdata
                                            mountPath: /usr/local/tomcat/webapps

                                          - name: mysqldata
                                            mountPath: /var/lib/mysql/

                                          - name: apachedata
                                            mountPath: /var/www/html/


                                - image: mysql:5.6
                                  imagePullPolicy: Always
                                  name: mysql
                                  env:

                                          - name: MYSQL_ROOT_PASSWORD
                                            value: YWRtaW4=

                                  ports:
                                          - containerPort: 3306
                                            name: mysql
                                  volumeMounts:
                                          - name: mysql-persistent-storage1
                                            mountPath: /var/lib/mysql/

                                - image: 192.168.0.6:5000/tomcatarch:2
                                  name: tomcat
                                  env:
                                          - name: MYSQL_ROOT_PASSWORD
                                            value: YWRtaW4=
                                  ports:
                                          - containerPort: 8080
                                            name: tomcat

                                  volumeMounts:

                                          - name: tomcat-persistent-storage1
                                            mountPath: /usr/local/tomcat/webapps




                        volumes:
                                - name: mysql-persistent-storage1
                                  persistentVolumeClaim:
                                          claimName: mysql-persistent-storage1
                                - name: apache-persistent-storage1
                                  persistentVolumeClaim:
                                          claimName: apache-persistent-storage1
                                - name: tomcat-persistent-storage1
                                  persistentVolumeClaim:
                                          claimName: tomcat-persistent-storage1

                                - name: mysqldata
                                  hostPath:
                                          path: /var/lib/mysql
                                - name: apachedata
                                  hostPath:
                                          path:  /var/www/html
                                - name: tomcatdata
                                  hostPath:
                                          path: /usr/local/tomcat/webapps


