# CREATE PERSISTENT VOLUMES FOR JOOMLA AND MYSQL
apiVersion: v1
kind: PersistentVolume
metadata:
        name: joomla-persistent-storage1
        namespace: kube-system
        labels:
                app: joomla
                tier: frontend
spec:
        capacity:
                storage: 2Gi
        accessModes:
                - ReadWriteMany
        hostPath:
                path: "/var/www/html"
---

apiVersion: v1
kind: PersistentVolume
metadata:
        name: mysql-persistent-storage1
        namespace: kube-system
        labels:
                app: joomla
                tier: mysql
spec:
        capacity:
                storage: 2Gi
        accessModes:
                - ReadWriteMany
        hostPath:
                path: "/var/lib/mysql"


---

apiVersion: v1
kind: PersistentVolume
metadata:
        name: smtp-persistent-storage1
        namespace: kube-system
        labels:
                app: joomla
                tier: smtp
spec:
        capacity:
                storage: 2Gi
        accessModes:
                - ReadWriteMany
        hostPath:
                path: "/var/mail"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: joomla-persistent-storage1
        namespace: kube-system
        labels:
                app: joomla
                tier: frontend
spec:
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 1Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: mysql-persistent-storage1
        namespace: kube-system
        labels:
                app: joomla
                tier: mysql
spec:
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 1Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: smtp-persistent-storage1
        namespace: kube-system
        labels:
                app: joomla
                tier: smtp

spec:
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
        name: joomla-mysql
        namespace: kube-system
        labels:
                app: joomla
spec:
        type: NodePort

        ports:
                - { nodePort: 30021, port: 21, targetPort: 21, name: ftpconn }
                - { nodePort: 32020, port: 20, targetPort: 21, name: ftpdata }  
                - { nodePort: 30091, port: 30091, targetPort: 30091, name: pasv1 }
                - { nodePort: 30092, port: 30092, targetPort: 30092, name: pasv2 }
                - { nodePort: 30093, port: 30093, targetPort: 30093, name: pasv3 }
                - { nodePort: 30094, port: 30094, targetPort: 30094, name: pasv4 }
                - { nodePort: 30095, port: 30095, targetPort: 30095, name: pasv5 }
                - { nodePort: 30096, port: 30096, targetPort: 30096, name: pasv6 }
                - { nodePort: 30097, port: 30097, targetPort: 30097, name: pasv7 }
                - { nodePort: 30098, port: 30098, targetPort: 30098, name: pasv8 }
                - { nodePort: 30099, port: 30099, targetPort: 30099, name: pasv9 }
                - { nodePort: 30100,port: 30100, targetPort: 30100, name: pasv10 }

                - nodePort: 32022
                  name: "22"
                  port: 22
                  targetPort: 22

                - nodePort: 32000
                  name: "80"
                  port: 80
                  targetPort: 80 
    
        selector:
                app: joomla
                tier: mysql
       

 
---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: joomla-mysql
        namespace: kube-system
        labels:
                app: joomla
spec:
        selector:
                matchLabels:
                        app: joomla
                        tier: mysql

        strategy:
                type: Recreate
        template:
                metadata:
                        labels:
                                app: joomla
                                tier: mysql

                spec:
                        containers:

                                - image: 192.168.1.3:5000/ftparch:2
                                  name: ftparch
                                  ports:
                                          - containerPort: 21
                                            name: ftp
                                  volumeMounts:
                                          - name: smtpdata
                                            mountPath: /var/mail
                       
                                          - name: mysqldata
                                            mountPath: /var/lib/mysql

                                          - name: joomladata
                                            mountPath: /var/www/html
      

                                - image: 192.168.1.3:5000/smtparch:2
                                  name: smtp
                                  ports:
                                          - containerPort: 25

                                  volumeMounts:
                                          - name: smtp-persistent-storage1
                                            mountPath: /var/mail/



                                - image: 192.168.1.3:5000/ssharch:2
                                  name: sshd
                                  ports:
                                          - containerPort: 22
                                            name: sshd
                                  volumeMounts:

                                          - name: smtpdata
                                            mountPath: /var/mail

                                          - name: mysqldata
                                            mountPath: /var/lib/mysql/
                                  
                                          - name: joomladata
                                            mountPath: /var/www/html/
                                            

                                - image: mysql:5.6
                                  imagePullPolicy: Always
                                  name: mysql
                                  env:
                
                                          - name: MYSQL_ROOT_PASSWORD
                                            value: YWRtaW4=
                         
                                  ports:
                                          - containerPort: 3306
                                            name: mysql
                                  volumeMounts:
                                          - name: mysql-persistent-storage1
                                            mountPath: /var/lib/mysql/

                                - image: 192.168.1.6:5000/joomlaarch:2
                                  name: joomla
                                  env:
                                          - name: JOOMLA_DB_HOST
                                            value: 127.0.0.1
                                          - name: JOOMLA_DB_PASSWORD
                                            value: YWRtaW4=
                                          - name: JOOMLA_DB_USER
                                            value: root

                                  ports:
                                          - containerPort: 80
                                            name: joomla

                                  volumeMounts:

                                          - name: joomla-persistent-storage1
                                            mountPath: /var/www/html/

                                          



                        volumes:
                                - name: mysql-persistent-storage1
                                  persistentVolumeClaim:
                                          claimName: mysql-persistent-storage1
                                - name: joomla-persistent-storage1
                                  persistentVolumeClaim:
                                          claimName: joomla-persistent-storage1
                                - name: smtp-persistent-storage1
                                  persistentVolumeClaim:
                                          claimName: smtp-persistent-storage1

                                - name: mysqldata
                                  hostPath:
                                          path: /var/lib/mysql
                                - name: joomladata
                                  hostPath:
                                          path:  /var/www/html
                                - name: smtpdata
                                  hostPath:
                                          path: /var/mail


