# CREATE PERSISTENT VOLUMES FOR JOOMLA AND MYSQL
---

apiVersion: v1
kind: PersistentVolume
metadata:
        name: mysql-persistent-storage1
        labels:
                app: radius
                tier: mysql
spec:
        capacity:
                storage: 2Gi
        accessModes:
                - ReadWriteMany
        hostPath:
                path: "/var/lib/mysql"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: mysql-persistent-storage1
        labels:
                app: radius
                tier: mysql
spec:
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
        name: radius-mysql
        labels:
                app: radius
spec:
        type: NodePort

        ports:
                - nodePort: 30000
                  name: "3306"
                  port: 3306
                  targetPort: 3306
                - nodePort: 32014
                  name: "3389"
                  port: 3389
                  targetPort: 3389                
                - nodePort: 32007
                  name: "1812"
                  port: 1812
                  protocol: UDP
                  targetPort: 1812
                - nodePort: 32008
                  name: "18120"
                  port: 18120
                  protocol: UDP
                  targetPort: 18120
                - nodePort: 32009
                  name: "1813"
                  port: 1813
                  protocol: UDP
                  targetPort: 1813
                - nodePort: 32022
                  name: "22"
                  port: 22
                  targetPort: 22

        selector:
                app: radius
                tier: mysql
      
---

apiVersion: apps/v1
kind: Deployment
metadata:
        name: radius-mysql
        labels:
                app: radius
spec:
        selector:
                matchLabels:
                        app: radius
                        tier: mysql

        strategy:
                type: Recreate
        template:
                metadata:
                        labels:
                                app: radius
                                tier: mysql

                spec:
                        containers:

                                - image: 192.168.1.5:5000/xrdp:latest
                                  name: xrdp
                                  ports:
                                          - containerPort: 3389

                                - image: 192.168.1.5:5000/radius:latest
                                  name: radius
                                  env:
                                          - name: DB_HOST
                                            value: '127.0.0.1'
                                          - name: DB_PORT
                                            value: '3306'
                                          - name: DB_USER
                                            value: root
                                          - name: DB_PASS
                                            value: YWRtaW4=
                                          - name: DB_NAME
                                            value: radius
                                  ports:
                                          - containerPort: 1812
                                            name: radiusa
                                          - containerPort: 1813
                                            name: radiusb
                                          - containerPort: 18120
                                            name: radiusc
                                 
                     


                                - image: 192.168.1.3:5000/ssharch:2
                                  name: sshd
                                  ports:
                                          - containerPort: 22
                                            name: sshd
                                  volumeMounts:
                   
                                          - name: mysqldata
                                            mountPath: /var/lib/mysql/

                                                              

                                - image: 192.168.1.5:5000/mysql:latest
                                  imagePullPolicy: Always
                                  name: mysql
                                  env:
                
                                          - name: MYSQL_ROOT_PASSWORD
                                            value: YWRtaW4=
                                          - name: MYSQL_DATABASE
                                            value: radius
                         
                                  ports:
                                          - containerPort: 3306
                                            name: mysql
                                  volumeMounts:
                                          - name: mysql-persistent-storage1
                                            mountPath: /var/lib/mysql/

          
                                          



                        volumes:
                                - name: mysql-persistent-storage1
                                  persistentVolumeClaim:
                                          claimName: mysql-persistent-storage1

                                - name: mysqldata
                                  hostPath:
                                          path: /var/lib/mysql

                             

            
