---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ftpservice
  name: ftpservice
spec:
  type: NodePort
  ports:
  - { nodePort: 30021, port: 21, targetPort: 21, name: ftp }
  - { nodePort: 30091, port: 30091, targetPort: 30091, name: pasv1 }
  - { nodePort: 30092, port: 30092, targetPort: 30092, name: pasv2 }
  - { nodePort: 30093, port: 30093, targetPort: 30093, name: pasv3 }
  - { nodePort: 30094, port: 30094, targetPort: 30094, name: pasv4 }
  - { nodePort: 30095, port: 30095, targetPort: 30095, name: pasv5 }
  - { nodePort: 30096, port: 30096, targetPort: 30096, name: pasv6 }
  - { nodePort: 30097, port: 30097, targetPort: 30097, name: pasv7 }
  - { nodePort: 30098, port: 30098, targetPort: 30098, name: pasv8 }
  - { nodePort: 30099, port: 30099, targetPort: 30099, name: pasv9 }
  - { nodePort: 30100,port: 30100, targetPort: 30100, name: pasv10 }
  selector:
    app.kubernetes.io/name: ftpservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ftpservice
  name: ftpservice
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ftpservice
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ftpservice
    spec:
      containers:
      - name: ftpservice
        image: 192.168.56.1:5000/ftpnew:2
        ports:
        - containerPort: 21
        - containerPort: 30091
        - containerPort: 30092
        - containerPort: 30093
        - containerPort: 30094
        - containerPort: 30095
        - containerPort: 30096
        - containerPort: 30097
        - containerPort: 30098
        - containerPort: 30099
        - containerPort: 30100
        
